### ISSUE TITLE
Invalid config

### ISSUE THREAD

**Issue by cleme-si** [asev/homeassistant-helios#1]
I  am trying to setup a connection to KWL300 ET, however with an issue. The HA notifies there is invalid config: 

like: 

Invalid config
The following integrations and platforms could not be set up:
helios

Could it be that eazyctrl.py is missing somehow? I have copied it into the folder ../config/custom_components/helios.

**Comment by killee** [comment]
I've the same problem to get this running.

**Comment by killee** [comment]
Okay with the update it works! Thanks a lot!

**Comment by asev** [comment]
Thanks @killee for letting me know.
Usually such problem appears because of missing manifest.json. I'm adding this integration to HACS to make installation process easier. This should also help to avoid situations when some files are not copied.
Feel free to reopen the issue if you face this problem again.
